N_VARIANTS: 5
JS: [300]
RS: [0.25]
SUSTAIN_FOLDER: 'bebms/test/sustain_results/results'
MY_FOLDER: 'bebms/test/algo_results/results'
TEMPERATURE_LO: 0.01
TEMPERATURE_HI: 0.35
N_SUB_LO: 1
N_SUB_HI: 1
GEN_DIRICHLET_PRIORS: [0.1, 2, 5, 20]
SUBTYPE_LENGTH_LO: 5 # the lowest possible number of diseased participant any subtype can have 
EXPERIMENT_NAMES:
  # - sn_kjOrdinalDM_xnjNormal                  # Experiment 1: Ordinal k_j, Dirichlet-Multinomial stage prior, Normal biomarker distributions
  # - sn_kjOrdinalDM_xnjNonNormal               # Experiment 2: Ordinal k_j, Dirichlet-Multinomial stage prior, Non-Normal biomarker distributions
  # - sn_kjOrdinalUniform_xnjNormal             # Experiment 3: Ordinal k_j, Uniform stage prior, Normal biomarker distributions
  # - sn_kjOrdinalUniform_xnjNonNormal          # Experiment 4: Ordinal k_j, Uniform stage prior, Non-Normal biomarker distributions
  # - sn_kjContinuousUniform_sigmoid            # Experiment 5: Continuous k_j (Uniform distribution), sigmoid measurement model
  # - sn_kjContinuousBeta_sigmoid               # Experiment 6: Continuous k_j (Beta distribution), sigmoid measurement model
  # - sn_kjContinuousUniform_xnjNormal          # Experiment 7: Continuous k_j (Uniform distribution), Normal biomarker distributions
  # - sn_kjContinuousUniform_xnjNonNormal       # Experiment 8: Continuous k_j (Uniform distribution), Non-Normal biomarker distributions
  # - sn_kjContinuousBeta_xnjNormal             # Experiment 9: Continuous k_j (Beta distribution), Normal biomarker distributions
  # - sn_kjContinuousBeta_xnjNonNormal          # Experiment 10: Continuous k_j (Beta distribution), Non-Normal biomarker distributions
  - xiNearNormal_kjContinuousBeta_sigmoid     # Experiment 11: Continuous xi (near-normal), Continuous k_j (Beta), sigmoid measurement model
  # - xiNearNormal_kjContinuousBeta_xnjNormal   # Experiment 12: Continuous xi (near-normal), Continuous k_j (Beta), EBM framework with Normal biomarker distributions

  
MP_SAMPLE_COUNT: 1
MP_MCMC: 300
N_MCMC: 20000
N_SHUFFLE: 2
BURN_IN: 200
THINNING: 1
GEN_SEED: 53
TIMES_MORE: 3
LOW_NUM: 2
HIGH_NUM: 4 
MCMC_SEED: 42
OUTPUT_DIR: 'algo_results'
